# Generated by Django 4.2.1 on 2023-06-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doas',
            name='cpf',
            field=models.IntegerField(default=11, max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doas',
            name='img',
            field=models.ImageField(default=1000, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doas',
            name='nome',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='doas',
            name='num',
            field=models.IntegerField(max_length=13),
        ),
    ]
