# Generated by Django 4.2.2 on 2023-06-28 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_doas_cpf_doas_img_alter_doas_nome_alter_doas_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doas',
            name='img',
        ),
    ]
