# Generated by Django 4.2.2 on 2023-06-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_doas_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='doas',
            name='img',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
